name: luckygo_pemandu
description: A new Flutter project with Firebase integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.12
  shared_preferences: ^2.0.0
  device_info_plus: ^10.1.0
  geoflutterfire_plus: ^0.0.32
  dart_geohash: ^2.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.0            # or newer
  image_picker_android: ^0.8.0     # add this line (any recent)
  image_picker_platform_interface: ^2.10.0
  firebase_storage: ^12.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  permission_handler: ^11.3.1
  geolocator: ^11.1.0
  http: ^1.2.1
  share_plus: ^11.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_launcher_icons: ^0.13.1
  qr_flutter: ^4.1.0
  firebase_dynamic_links: ^6.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/luckygo_logo.png
    - assets/images/special2.png
    - assets/images/wheelchair.png
    - assets/images/blind_symbol.png
    - assets/images/deaf_symbol.png
    - assets/images/ind_supportstick.png
    - assets/images/mute_symbol.png
    - assets/images/stroller.png
    - assets/images/ind_stroller.png
    - assets/images/shopping_1.png
    - assets/images/shopping_2.png
    - assets/images/shopping_3.png
    - assets/images/shopping_4.png
    - assets/images/shopping_5.png
    - assets/images/luggage_1.png
    - assets/images/luggage_2.png
    - assets/images/luggage_3.png
    - assets/images/luggage_4.png
    - assets/images/luggage_5.png
    - assets/images/ind_adult.png
    - assets/images/ind_baby.png
    - assets/images/ind_wheelchair.png
    - assets/images/ind_shopping1.png
    - assets/images/ind_shopping2.png
    - assets/images/ind_shopping3.png
    - assets/images/ind_shopping4.png
    - assets/images/ind_shopping5.png
    - assets/images/ind_luggage1.png
    - assets/images/ind_luggage2.png
    - assets/images/ind_luggage3.png
    - assets/images/ind_luggage4.png
    - assets/images/ind_luggage5.png
    - assets/images/ind_pets.png
    - assets/images/ind_dog.png
    - assets/images/ind_goat.png
    - assets/images/ind_rooster.png
    - assets/images/ind_snake.png
    - assets/images/ind_durian.png
    - assets/images/ind_odourfruits.png
    - assets/images/ind_wetfood.png
    - assets/images/ind_tupperware.png
    - assets/images/ind_gastank.png
    - assets/images/presenter.png
    - assets/images/ind_passenger.png
    - assets/images/destination_marker.png
    - assets/images/earth.png
    - assets/images/aim_1.png
    - assets/images/d1.png
    - assets/images/d2.png
    - assets/images/d3.png
    - assets/images/d4.png
    - assets/images/d5.png
    - assets/images/car.png
    - assets/images/finish.png
    - assets/images/doc_front.png
    - assets/images/doc_back.png
    - assets/images/doc_ic.png
    - assets/images/doc_insurance.png
    - assets/images/doc_kad_kereta.png
    - assets/images/doc_lesen_memandu.png
    - assets/images/doc_psv.png
    - assets/images/doc_selfie.png
    - assets/images/doc_roadtax.png
    - assets/images/pin.png
    - assets/images/tips.png
    - assets/images/rhb_logo.png
    - assets/images/maybank_logo.png
    - assets/images/public_bank_logo.png
    - assets/images/cimb_bank_logo.png
    - assets/images/hong_leong_bank_logo.png
    - assets/images/alliance_bank_logo.png
    - assets/images/bsn_logo.png
    - assets/images/geofencing.png
    - assets/images/nearest_exit.png
    - assets/images/luckygo_icon.png

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: assets/images/luckygo_icon.png
  remove_alpha_ios: true
  min_sdk_android: 21